//! Per-session state: persisted KV records and live in-memory runtime.
//!
//! Two layers of state coexist:
//!
//! - [`SessionRecord`] — JSON, persisted to KV under `sage.session.<sid>`
//!   keyed by session_id. Survives capsule unload; the records are the
//!   recovery list scanned on supervisor start.
//! - [`RuntimeSession`] — live in-memory state, including the
//!   [`process::Process`] resource handle (which is a kernel resource
//!   NOT serializable to KV) plus the stream-json line decoder buffer
//!   and pending tool-call bookkeeping. Held in a [`Mutex<HashMap>`]
//!   inside the capsule singleton; dies on capsule reload.
//!
//! On reload, persisted records exist but their `Process` handles are
//! gone — the supervisor tick reconciles by synthesising
//! `sage.v1.event.<sid>.exited{reason:"capsule_reload"}` events and
//! clearing the orphan records before serving any new spawn.

use crate::codec;
use astrid_sdk::prelude::*;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::{Arc, Mutex};

/// KV key prefix for sage session records.
pub(crate) const SESSION_KEY_PREFIX: &str = "sage.session";

/// Per-principal cap on concurrently active sessions.
///
/// Set to 4 — well under the 8-process-per-capsule host ceiling so
/// `sage-install` scratch spawns still have headroom even at full
/// session occupancy.
pub(crate) const MAX_SESSIONS_PER_PRINCIPAL: usize = 4;

/// KV key for a session's persisted record.
pub(crate) fn session_key(session_id: &str) -> String {
    format!("{SESSION_KEY_PREFIX}.{session_id}")
}

// NOTE: There is intentionally no sage-side install-complete key here.
// Earlier revisions defined `install_complete_key` and had
// `ensure_install` short-circuit on it, but the kernel scopes KV by
// `{principal}:capsule:{capsule_id}` — sage and sage-install are
// distinct capsule_ids with disjoint KV namespaces. The marker lives in
// sage-install's namespace exclusively; sage gates on the published
// `sage.v1.install.complete` event whose `already_installed: true`
// flag is the cache-hit signal. See `lib.rs::ensure_install`.

/// Persisted session bookkeeping. Restored from KV on capsule load.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub(crate) struct SessionRecord {
    pub principal_id: String,
    pub session_id: String,
    pub identity_path: String,
    pub started_at_ms: u64,
    /// Stamped at spawn for audit correlation; not load-bearing for
    /// behaviour, just observability.
    pub os_pid: u32,
}

/// Live, non-serializable session state held in capsule memory.
///
/// The `process::Process` handle is a kernel resource (component-model
/// `resource`) — it cannot survive capsule reload. Pairs with a
/// [`SessionRecord`] in KV that records the durable metadata.
///
/// `process` is held in an `Arc` so a handle can be cloned out of the
/// [`Sessions`] mutex critical section before issuing host calls
/// (`write_stdin`, `read_logs`, etc.). All those calls take `&self`, so
/// concurrent access through the `Arc` is safe; the kernel resource
/// itself serialises stdin writes internally. Holding the `Sessions`
/// mutex across host calls would serialise the whole supervisor loop
/// and risk deadlock if the host call re-enters the bus drain — the
/// `Arc` cloning pattern in [`crate::tooling`] is the supported escape.
pub(crate) struct RuntimeSession {
    pub record: SessionRecord,
    pub process: Arc<process::Process>,
    pub codec: codec::LineDecoder,
    /// Outstanding tool calls awaiting results, keyed by `call_id`
    /// (UUIDv4 generated by the supervisor at dispatch). Each entry
    /// carries the monotonic dispatch timestamp (for deadline aging)
    /// AND the correlation needed to route the result back to claude in
    /// the right wire shape — see [`Correlation`] for why this matters.
    ///
    /// The `call_id` is sage's internal handle for the bus round-trip.
    /// It is NOT the value claude expects to see echoed back: claude's
    /// `sdk_control_request.request_id` (MCP path) or the assistant's
    /// `tool_use_id` (tool_use path) is a different identifier the
    /// supervisor captures here at dispatch time. External tool
    /// responders only ever see `call_id` on
    /// `sage.v1.tool.result.<call_id>`; sage reconstitutes the
    /// correlation when encoding the write-back frame so provider-
    /// specific ids never leak onto the bus.
    pub pending_tool_calls: HashMap<String, PendingCall>,
    /// Partially-streamed tool_use input_json, keyed by Anthropic's
    /// `tool_use_id`. Accumulated across content_block_delta events
    /// until the matching content_block_stop fires. Stores the running
    /// `(name, input_json)` pair so the supervisor can publish the
    /// canonical tool.call when the stop event arrives.
    pub partial_tool_inputs: HashMap<String, PartialTool>,
}

/// Tracking state for one in-flight tool call.
///
/// The `call_id` (UUIDv4) is what sage mints to address the bus round-
/// trip and is the key into [`RuntimeSession::pending_tool_calls`]; it
/// is NOT what claude expects to see echoed back. The [`Correlation`]
/// field carries whichever upstream identifier the result envelope
/// must reference so claude can match the response to its outstanding
/// request.
#[derive(Debug, Clone)]
pub(crate) struct PendingCall {
    /// Monotonic-millis dispatch time. Compared against
    /// `crate::TOOL_CALL_DEADLINE` by `tooling::enforce_deadlines`.
    pub started_ms: u64,
    /// Which upstream identifier the result frame must echo. The two
    /// variants take different stream-json shapes — see [`Correlation`].
    pub correlation: Correlation,
}

/// How a tool call was originated, which dictates the wire shape of the
/// result envelope written back to claude's stdin.
///
/// The MCP control-request path and the assistant tool_use path look
/// superficially identical from the bus side (both flow through
/// `sage.v1.tool.call.<call_id>` / `sage.v1.tool.result.<call_id>`) but
/// require structurally different result frames:
///
/// * `McpControl` answers with a `control_response` carrying the
///   `mcp_response` wrapper, keyed on claude's original
///   `sdk_control_request.request_id` — NOT sage's `call_id`.
/// * `ToolUse` answers with a `user`-role message whose content is a
///   single `tool_result` block keyed on the assistant's `tool_use_id`.
///
/// Mixing them up causes claude to time out at 60 s waiting for a
/// matching response that never arrives.
#[derive(Debug, Clone)]
pub(crate) enum Correlation {
    /// Reply to an `sdk_control_request{subtype:"mcp_message"}`. The
    /// stored id is the value claude put in its request's `request_id`
    /// field; it is what `control_response.response.request_id` must
    /// echo back.
    McpControl { claude_request_id: String },
    /// Reply to an assistant `tool_use` content block. The stored id is
    /// the `tool_use_id` from the assistant message; the response is a
    /// `user`-role envelope with a `tool_result` block keyed by it.
    ToolUse { tool_use_id: String },
}

/// Accumulator for a single in-flight Anthropic tool_use content block.
#[derive(Debug, Default, Clone)]
pub(crate) struct PartialTool {
    pub name: String,
    pub input_json: String,
}

/// Singleton in-memory registry of live sessions. Behind a `Mutex` for
/// interior mutability since handler entry points take `&self` (the
/// `#[capsule]` macro requires non-mutable receivers when no method
/// uses `&mut self`).
#[derive(Default)]
pub(crate) struct Sessions {
    inner: Mutex<HashMap<String, RuntimeSession>>,
    /// One-shot flag: the supervisor's first tick after capsule load
    /// scans KV for orphaned records and emits synthetic
    /// `capsule_reload` exit events. We don't want to repeat that scan
    /// on every tick.
    reload_recovered: Mutex<bool>,
}

impl Sessions {
    /// Borrow the live session map for direct mutation.
    pub(crate) fn with<R>(
        &self,
        f: impl FnOnce(&mut HashMap<String, RuntimeSession>) -> R,
    ) -> Result<R, SysError> {
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| SysError::ApiError("sage session registry lock poisoned".into()))?;
        Ok(f(&mut guard))
    }

    /// Count active sessions for a principal — enforces the per-principal cap.
    pub(crate) fn count_for_principal(&self, principal_id: &str) -> Result<usize, SysError> {
        self.with(|map| {
            map.values()
                .filter(|s| s.record.principal_id == principal_id)
                .count()
        })
    }

    /// True the first time it is called after capsule load; false thereafter.
    /// Used to gate the orphan-record recovery scan to a single execution.
    pub(crate) fn take_reload_recovered_flag(&self) -> Result<bool, SysError> {
        let mut guard = self
            .reload_recovered
            .lock()
            .map_err(|_| SysError::ApiError("sage reload-recovery flag lock poisoned".into()))?;
        if *guard {
            Ok(false)
        } else {
            *guard = true;
            Ok(true)
        }
    }
}

/// Persist a session record to KV.
pub(crate) fn save_record(rec: &SessionRecord) -> Result<(), SysError> {
    kv::set_json(&session_key(&rec.session_id), rec)
}

/// Delete a session's KV record.
pub(crate) fn delete_record(session_id: &str) -> Result<(), SysError> {
    kv::delete(&session_key(session_id))
}

/// Enumerate every persisted session record by scanning the KV prefix.
pub(crate) fn list_all_records() -> Result<Vec<SessionRecord>, SysError> {
    let keys = kv::list_keys(&format!("{SESSION_KEY_PREFIX}."))?;
    let mut out = Vec::with_capacity(keys.len());
    for key in keys {
        if let Some(rec) = kv::get_json_opt::<SessionRecord>(&key)? {
            out.push(rec);
        }
    }
    Ok(out)
}
